Repository savoirfairelinux/project-addons, pull requests merged in 2018-11, with the labels that each got.

#157 [ADD] Confirm reservation event
  project_event/__manifest__.py
  project_event/models/project_task.py
  project_event/tests/test_project_event_task.py
  project_event/wizard/__init__.py
  project_event/wizard/reservation_validation_wiz.py
  project_event/wizard/reservation_validation_wiz_view.xml
  project_resource_calendar/models/resource.py
Labels: work in progress

#185 [ADD] Lmg add hached background on option calendar event
  project_event/models/calendar_event.py
  project_event/static/src/js/web_calendar_colour.js
  project_event/views/calendar_event_category_view.xml
Labels: has conflicts

#198 [ADD] Default Task start date is empty
  project_event/models/project_task.py
Labels: need review

#204 [ADD] Display double booking field for room and instrument
  project_resource_calendar/views/instrument_view.xml
  project_resource_calendar/views/room_view.xml
Labels: Approved

#208 [ADD] Disable adding items from event wizard
  project_event/wizard/project_event_wizard_view.xml
Labels: need review

#207 [ADD] Editable responsible for template
  project_event/i18n/fr.po
  project_event/models/activity_template.py
  project_event/models/task_template.py
  project_event/views/activity_template_view.xml
  project_event/views/task_template_view.xml
  project_event/wizard/project_activity_wizard.py
  project_event/wizard/project_event_wizard.py
  project_event/wizard/project_event_wizard_view.xml
  project_event/wizard/project_task_wizard.py
Labels: Approved

#209 [ADD] Change state label of project task
  project_event/i18n/fr.po
  project_event/models/project_task.py
Labels: Approved

#211 [ADD] Link calendar event to task
  project_event/models/project_task.py
  project_event/views/calendar_event_category_view.xml
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#202 [ADD] Default category to A,T #399
  project_event/data/task_categories.xml
  project_event/models/__init__.py
  project_event/models/calendar_event.py
  project_event/models/project_task.py
  project_event/models/task_category.py
  project_event/views/task_category_view.xml
Labels: need review

#212 [ADD] Fix date_start for compute task order
  project_event/models/project_task.py
Labels: need review

#213 [ADD] responsible in event tree view
  project_event/views/project_project_view.xml
Labels: need review

#214 [FIX] Fix succeeding task form view
  project_event/views/project_task_view.xml
Labels: need review

#215 [ADD] Added javascript saml error handler
  project_event/static/src/js/saml_error_handler.js
  project_event/templates/assets.xml
Labels: need review

#218 [ADD] ADD confirmation for accept and request
  project_event/models/project_project.py
  project_event/models/project_task.py
  project_event/tests/test_project_event_reservation.py
  project_event/tests/test_project_event_task.py
  project_event/wizard/reservation_validation_wiz.py
  project_event/wizard/reservation_validation_wiz_view.xml
Labels: need review

#225 [FIX] wizard decoupling task and event business logic
  project_event/models/project_project.py
  project_event/models/project_task.py
  project_event/wizard/reservation_validation_wiz.py
Labels: need review

#224 [FIX] Write method on task (enhacement + fix: tasks resposible only changes when activity resp changes)
  project_event/models/project_task.py
Labels: enhancement

#222 [ADD] Create the 'Client Type' in the Project Event
  project_event/__manifest__.py
  project_event/i18n/fr.po
  project_event/models/__init__.py
  project_event/models/project_project.py
  project_event/models/project_task.py
  project_event/models/res_partner_category.py
  project_event/models/res_partner_category_type.py
  project_event/security/ir.model.access.csv
  project_event/views/res_partner_category_type_view.xml
Labels: need review
