Repository savoirfairelinux/project-addons, pull requests merged in 2018-12, with the labels that each got.

#229 [ADD] Add employees of task to calendar event
  project_event/models/project_task.py
Labels: Approved

#226 [ADD] wizard event creation tests
  project_event/models/activity_template.py
  project_event/models/event_template.py
  project_event/models/task_template.py
  project_event/tests/__init__.py
  project_event/tests/common.py
  project_event/tests/test_activity_template.py
  project_event/tests/test_event_creation_from_wizard.py
  project_event/tests/test_task_template.py
Labels: need review

#235 [FIX] Write Event
  project_event/models/project_project.py
Labels: need review

#234 [ADD] Added required category in calendar
  project_event/views/calendar_event_category_view.xml
Labels: need review

#232 [ADD] Added editable equal false for calendar.event task clones
  project_event/static/src/js/web_calendar_colour.js
Labels: need review

#239 Display "Catetory field" in the Contacts/Configuration/Contact Tags form view
  project_event/__manifest__.py
  project_event/models/res_partner_category_type.py
  project_event/views/project_task_view.xml
  project_event/views/res_partner_category_type_view.xml
  project_event/views/res_partner_category_view.xml
  project_event/views/task_category_view.xml
Labels: need review

#241 [FIX]ResPartner Category translation
  project_event/models/res_partner_category.py
  project_event/models/res_partner_category_type.py
Labels: need review

#242 [FIX] Correction in the report calendar Event
  project_resource_calendar/report/calendar_event_print_template.xml
Labels: need review

#247 [FIX] Formview task/activity discuss
  project_event/models/__init__.py
  project_event/models/models.py
Labels: need review

#243 [FIX]Anolmalie when print calendar event report when selecting All day field
  project_resource_calendar/report/calendar_event_print_template.xml
Labels: need review

#246 [Fix] No create from succeeding
  project_event/views/project_task_view.xml
Labels: need review

#233 [ADD] Weekly report by room
  project_resource_calendar/__init__.py
  project_resource_calendar/__manifest__.py
  project_resource_calendar/wizard/__init__.py
  project_resource_calendar/wizard/weekly_report.py
  project_resource_calendar/wizard/weekly_report_template.xml
  project_resource_calendar/wizard/weekly_report_wizard.py
  project_resource_calendar/wizard/weekly_report_wizard.xml
Labels: need review

#248 [FIX] Preceding Succeding Visibility & Done status bar
  project_event/models/project_task.py
  project_event/views/project_task_view.xml
Labels: Answer, need review

#252 [FIX] Fix create task problem
  project_event/models/project_task.py
Labels: need review

#253 [ADD] Historisation Salle via Audit log
  project_resource_calendar/__manifest__.py
  project_resource_calendar/data/auditlog_rule.xml
  project_resource_calendar/models/room.py
  project_resource_calendar/views/auditlog_log.xml
  project_resource_calendar/views/room_view.xml
Labels: need review

#256 [ADD] Set Calendar Event status default to open
  project_resource_calendar/models/calendar_event.py
Labels: need review

#228 [ADD] Add Sector
  project_event/__manifest__.py
  project_event/i18n/fr.po
  project_event/models/__init__.py
  project_event/models/calendar_event.py
  project_event/models/project_project.py
  project_event/models/project_task.py
  project_event/models/res_partner.py
  project_event/models/res_partner_sector.py
  project_event/security/ir.model.access.csv
  project_event/tests/common.py
  project_event/tests/test_project_event.py
  project_event/tests/test_project_event_task.py
  project_event/views/calendar_event_category_view.xml
  project_event/views/project_project_view.xml
  project_event/views/project_task_view.xml
  project_event/views/res_partner_sector_view.xml
  project_event/views/res_partner_view.xml
Labels: need review

#258 [FIX ] Adding title to the instrument: becomes: Instruments / Equipment
  project_resource_calendar/i18n/fr.po
  project_resource_calendar/models/room.py
Labels: need review

#260 [ADD] ADD Employee category to room
  project_resource_calendar/models/room.py
  project_resource_calendar/views/room_view.xml
Labels: Approved, need review

#250 [ADD] Historisation Ressource via Audit log
  project_resource_calendar/data/auditlog_rule.xml
  project_resource_calendar/models/instrument.py
  project_resource_calendar/views/auditlog_log.xml
  project_resource_calendar/views/instrument_view.xml
Labels: need review

#257 [ADD] Langauge translation for Audit log Room model
  project_resource_calendar/i18n/fr.po
Labels: need review

#264 [FIX] Update Calendar Event Form and Pop up
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#262 [ADD] Integration of Unit Testing Test Cases for Calendar Event Model
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/__init__.py
  project_resource_calendar/tests/common.py
  project_resource_calendar/tests/test_calendar_event.py
  project_resource_calendar/tests/test_instrument.py
  project_resource_calendar/tests/test_room.py
Labels: work in progress

#270 [Fix] Reorganize code
  project_event/__manifest__.py
  project_event/static/src/css/calendar_style.css
  project_event/static/src/js/web_calendar_colour.js
  project_event/templates/assets.xml
  project_event/views/calendar_event_category_view.xml
  project_event/views/calendar_sidebar.xml
  project_event/views/project_task_view.xml
Labels: need review

#249 [FIX] Create project_task refactor
  project_event/models/project_task.py
  project_event/tests/test_project_event_task.py
Labels: need review

#271 [FIX] Test case Implementation for calendar event model:on_change_room_id method
  project_resource_calendar/tests/__init__.py
  project_resource_calendar/tests/common.py
  project_resource_calendar/tests/test_calendar_event.py
  project_resource_calendar/tests/test_instrument.py
  project_resource_calendar/tests/test_room.py
Labels: need review

#273 [Fix] is_from_template field and method
  project_event/models/project_task.py
Labels: need review

#272 [FIX] Date test problem
  project_event/tests/test_project_event_task.py
Labels: need review

#263 [FIX] By default, when a task is linked to an activity that has a category defined, the task should inherit the category of the Activity
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
Labels: need review

#265 [FIx] Related state triple history
  project_event/models/project_task.py
Labels: work in progress

#275 [FIX] Add we_timeline dependency
  project_event/__manifest__.py
  project_resource_calendar/__manifest__.py
Labels: need review

#277 [ADD] FIX create activity with tasks
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
Labels: need review

#278 [FIX] Sector Field on a Calendar.event should not be mandatory
  project_event/views/calendar_event_category_view.xml
Labels: need review

#280 [ADD] Add state color field
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: Approved

#276 [FIX] Refactory Calendar Event module Test case code
  project_resource_calendar/tests/__init__.py
  project_resource_calendar/tests/common.py
  project_resource_calendar/tests/test_calendar_event.py
  project_resource_calendar/tests/test_instrument.py
  project_resource_calendar/tests/test_room.py
Labels: need review

#282 [FIX] Project event tests
  project_event/tests/test_project_event_reservation.py
Labels: need review
