Repository savoirfairelinux/project-addons, pull requests merged in 2019-01, with the labels that each got.

#287 [ADD]Hide the fields Location, Categ_ids, alarm_ids in the calendar Event form
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#293 [ADD] ADD access rights groups for menus
  project_event/__manifest__.py
  project_event/data/channels.xml
  project_event/security/project_security.xml
  project_event/views/event_template_view.xml
  project_event/views/project_project_view.xml
  project_event/views/res_partner_category_type_view.xml
  project_event/views/res_partner_sector_view.xml
  project_event/wizard/project_event_wizard_view.xml
  project_resource_calendar/__manifest__.py
  project_resource_calendar/security/calendar_security.xml
  project_resource_calendar/views/equipment_calendar_view.xml
  project_resource_calendar/views/instrument_view.xml
  project_resource_calendar/views/room_type_view.xml
  project_resource_calendar/views/room_view.xml
  project_resource_calendar/wizard/weekly_report_template.xml
  project_resource_calendar/wizard/weekly_report_wizard.xml
Labels: Approved

#279 [FIX] Refactoring update_reseration_event
  project_event/models/project_task.py
Labels: need review

#288 [ADD] Display Category and Sector information in the Calendar Event pop-up Form
  project_event/models/calendar_event.py
  project_event/views/calendar_event_category_view.xml
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#289 ADD] Adding New Date fields in the Calendar Event Pop-up Menu form
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#291 [Add] Write Test case for update reservation event in project.task model (after method refactory)
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
Labels: need review

#300 [ADD] own resource reservation excluded
  project_event/models/project_task.py
Labels: need review

#297 [FIX] Refactoring is_new_activity() and is_new_task in project.task
  project_event/models/project_task.py
Labels: need review

#301 [ADD] project event access right
  project_event/security/ir.model.access.csv
  project_event/security/project_security.xml
  project_event/wizard/project_event_wizard_view.xml
Labels: need review

#304 [FIX] Message sent when status changed
  project_event/models/project_project.py
  project_event/wizard/reservation_validation_wiz.py
Labels: need review

#303 [ADD] Project Resource calendar access rules
  project_resource_calendar/security/calendar_security.xml
  project_resource_calendar/security/ir.model.access.csv
Labels: need review

#307 [FIX] Fix for calendar event form view
  project_event/models/project_task.py
  project_resource_calendar/i18n/fr.po
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#309 [FIX] Room and weekdays of recurrent events
  project_resource_calendar/views/equipment_calendar_view.xml
  project_resource_calendar/wizard/weekly_report.py
  project_resource_calendar/wizard/weekly_report_template.xml
Labels: need review

#311 [DEV] Test case for validating "recurrent_state" and "recurrent_type" in calendar module
  project_resource_calendar/tests/test_calendar_event.py
Labels: need review

#310 [FIX]View the full job name (TA00001 / Task Name)
  project_event/models/project_task.py
Labels: need review

#306 [ADD] Record rules for project event
  project_event/security/project_security.xml
  project_resource_calendar/security/calendar_security.xml
Labels: work in progress

#316 [ADD] Partner_id sync Calendar Event & Project Task
  project_event/models/calendar_event.py
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
Labels: Changes Request

#314 [ADD] Refactoring validate error message in project task
  project_event/models/project_task.py
Labels: need review

#317 [ADD] Group permission to change status
  project_event/security/ir.model.access.csv
  project_event/security/project_security.xml
  project_event/views/project_task_view.xml
  project_resource_calendar/security/calendar_security.xml
Labels: need review

#322 [ADD] Client to Calendar Event
  project_event/models/calendar_event.py
  project_event/models/project_task.py
  project_event/tests/test_project_event_reservation.py
  project_event/tests/test_project_event_task.py
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/templates/calendar_template.xml
Labels: Changes Request

#324 [ADD] Calendar Event Tree view fields
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#325 [FIX] Double booking fix
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/common.py
  project_resource_calendar/tests/test_calendar_event.py
Labels: need review

#323 [ADD] Security Test Setup
  project_event/security/ir.model.access.csv
  project_event/tests/__init__.py
  project_event/tests/test_security.py
  project_resource_calendar/security/calendar_security.xml
  project_resource_calendar/security/ir.model.access.csv
  project_resource_calendar/tests/__init__.py
  project_resource_calendar/tests/test_security.py
Labels: Changes Request

#326 [ADD] Lmg gant timeline cloned task no edit no delete
  project_resource_calendar/security/calendar_security.xml
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: need review

#330 [FIX] FIX current user partner
  project_event/models/project_task.py
  project_event/tests/test_project_event_reservation.py
  project_event/tests/test_project_event_task.py
  project_event/views/calendar_event_category_view.xml
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/views/equipment_calendar_view.xml
Labels: Approved
