Repository savoirfairelinux/project-addons, pull requests merged in 2019-03, with the labels that each got.

#353 Report "Activity's work slips" 3 sections
  project_event/__init__.py
  project_event/__manifest__.py
  project_event/models/models.py
  project_event/report/__init__.py
  project_event/report/project_task_activity_report.py
  project_event/report/project_task_activity_report.xml
Labels: need review

#356 [ADD] Using partner_ids for both clone task and calendar event
  project_resource_calendar/models/calendar_event.py
Labels: need review

#355 [FIX] Report format
  project_resource_calendar/wizard/weekly_report_template.xml
Labels: need review

#358 [FIX] Fix double booking for recurrent event
  project_resource_calendar/models/calendar_event.py
Labels: need review

#363 [FIX] Double booking and client_id fix
  project_resource_calendar/__manifest__.py
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#360 [ADD] Added is_bookable status for room and equipments for both calen…
  project_event/models/project_task.py
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/common.py
  project_resource_calendar/tests/test_security.py
Labels: need review

#361 [FIX] Set Resource type field invisible if it is not created from a task
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#359 [ADD] Removed acl for calendar timeline calendar event
  project_resource_calendar/security/calendar_security.xml
Labels: question, work in progress

#365 [ADD] Technical Sheet Resource section and template reformating
  project_event/report/project_task_activity_report.py
  project_event/report/project_task_activity_report.xml
Labels: need review

#368 [FIX] Action buttons access level
  project_event/views/project_task_view.xml
Labels: need review

#369 [FIX] Fix add followers error
  project_event/models/project_task.py
Labels: need review

#370 [FIX] ACL wirte permission project user on calendar event
  project_event/security/ir.model.access.csv
  project_event/tests/test_security.py
Labels: need review

#366 [FIX] Set Resource type field invisible if it is not created …
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#352 [ADD] Add section Time spent tasks
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
  project_event/views/project_task_view.xml
Labels: need review

#371 [FIX] Hide resources from calendar event view
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#373 [FIX] Calendar event creation problem for calendar editor
  project_event/security/ir.model.access.csv
Labels: need review

#372 [FIX] Fields order calendar event tree view
  project_resource_calendar/i18n/fr.po
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#347 [ADD] Added clone task changes status and child task
  project_event/models/project_task.py
  project_event/tests/test_project_event_task.py
  project_event/views/project_task_view.xml
Labels: need review

#375 [FIX] Fix synchronisation between project task and calendar event clone
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_reservation.py
Labels: need review

#374 [FIX] Font size client_id, room_id, resource_ids, partner_ids on calendar
  project_event/views/calendar_event_category_view.xml
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#377 [FIX] Fix Client type for calendar event
  project_event/models/calendar_event.py
  project_event/tests/__init__.py
  project_event/tests/common.py
  project_event/tests/test_calendar_event.py
  project_event/views/calendar_event_category_view.xml
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/test_calendar_event.py
Labels: need review

#380 [FIX] FIX added client to participants if it is a clone
  project_resource_calendar/models/calendar_event.py
Labels: need review

#367 [FIX]One-time reservation printing
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/report/calendar_event_print_template.xml
  project_resource_calendar/report/calendar_event_report.xml
Labels: need review

#382 [ADD] Is main task colored in the template task view
  project_event/i18n/fr.po
  project_event/models/project_task.py
  project_event/models/task_template.py
  project_event/views/task_template_view.xml
Labels: need review

#381 [ADD]New Features: 'Spectators' entry in the activity form
  project_event/i18n/fr.po
  project_event/models/project_task.py
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
  project_event/views/calendar_event_category_view.xml
  project_event/views/project_task_view.xml
  project_resource_calendar/views/calendar_event_view.xml
Labels: 1.1, need review

#386 [Technique]Clean Code
  project_event/models/mail_tracking_value.py
  project_event/models/project_task.py
  project_event/report/project_task_activity_report.py
  project_resource_calendar/tests/test_weekly_report_wizard.py
Labels: need review

#385 [ADD] Add filter on room level
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/test_calendar_event.py
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#387 [ADD] Added client_id and participants based on is_task_event
  project_resource_calendar/views/calendar_event_view.xml
Labels: need review

#390 [DEL] Deleted fields from configuration for ACAD and PROD
  project_event/security/project_security.xml
Labels: need review

#388 [FIX] Fix report for recurrent event
  project_resource_calendar/models/__init__.py
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/models/ir_actions_report.py
  project_resource_calendar/report/calendar_event_print_template.xml
Labels: work in progress

#391 [FIX] Fix Filter by Floor remove floor store true
  project_resource_calendar/models/calendar_event.py
Labels: need review

#392 [FIX] Fix client_id and partners_ids names calendar view
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/test_calendar_event.py
  project_resource_calendar/views/calendar_event_view.xml
Labels: Changes Request

#393 [FIX] Delete action clear from activity template
  project_event/models/activity_template.py
  project_event/tests/test_activity_template.py
  project_event/views/activity_template_view.xml
Labels: need review

#394 [FIX] Fix client_id and partners_ids names calendar view
  project_resource_calendar/models/calendar_event.py
  project_resource_calendar/tests/test_calendar_event.py
Labels: need review

#398 [ADD] Datatable Widget
  .circleci/config.yml
  project_event/__manifest__.py
  project_event/models/project_task.py
  project_event/views/project_task_view.xml
Labels: 1.1, need review

#402 [FIX] Test case for Actual Total time computation
  project_event/tests/common.py
  project_event/tests/test_project_event_task.py
Labels: need review

#400 [ADD] Timesheet task integration
  project_event/__manifest__.py
  project_event/i18n/fr.po
  project_event/models/__init__.py
  project_event/models/hr_timesheet.py
  project_event/models/project_task.py
  project_event/tests/test_project_event_task.py
  project_event/views/project_task_view.xml
Labels: need review

#406 [FIX] TimeZone Format of activity report
  project_event/report/project_task_activity_report.py
Labels: need review

#378 [ADD] V1.1 11.0_develop
  .circleci/config.yml
  project_event/__manifest__.py
  project_event/i18n/fr.po
  project_event/models/project_task.py
  project_event/report/project_task_activity_report.py
  project_event/report/project_task_activity_report.xml
  project_event/tests/test_project_event_task.py
  project_event/views/project_task_view.xml
  project_resource_calendar/wizard/weekly_report.py
Labels: 1.1, need review
